version: '3.8'

x-common: &common
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  # PostgreSQL数据库服务
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: feetfit_db
    <<: *common
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "holistic_user", "-d", "holistic_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-scripts:/docker-entrypoint-initdb.d
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    networks:
      - feetfit_network
    environment:
      - POSTGRES_USER=holistic_user
      - POSTGRES_PASSWORD=holistic_password
      - POSTGRES_DB=holistic_db
      - TZ=Asia/Shanghai
      - ENV=${ENV:-development}

  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: feetfit_backend
    <<: *common
    ports:
      - "3080:3080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - feetfit_network
    environment:
      - PYTHONPATH=/app
      - ENV=${ENV:-development}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=holistic_user
      - DB_PASSWORD=holistic_password
      - DB_NAME=holistic_db

  # 前端Web服务
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: feetfit_frontend
    <<: *common
    ports:
      - "3060:3060"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3060"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - ./pressure-viz-web:/app
      - /app/node_modules
      - /app/.next
    networks:
      - feetfit_network
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:3080

networks:
  feetfit_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1

volumes:
  postgres_data:
    driver: local
  node_modules:
    driver: local
